# Generated by Django 6.0 on 2026-01-05 15:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategoriya nomi')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Yangiliklar kategoriyasi',
                'verbose_name_plural': 'Yangiliklar kategoriyalari',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('slug', models.SlugField(max_length=200, unique_for_date='publish_date', verbose_name='Slug')),
                ('short_description', models.TextField(max_length=300, verbose_name='Qisqa tavsif')),
                ('content', models.TextField(verbose_name='Mazmuni')),
                ('image', models.ImageField(upload_to='news/%Y/%m/%d/', verbose_name='Rasm')),
                ('image_alt', models.CharField(blank=True, max_length=200, verbose_name='Rasm alternativ matni')),
                ('featured', models.CharField(choices=[('normal', 'Oddiy'), ('main', 'Asosiy'), ('secondary', 'Ikkinchi darajali')], default='normal', max_length=20, verbose_name='Muhimlik darajasi')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('published', 'Nashr etilgan')], default='draft', max_length=20, verbose_name='Holati')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Nashr sanasi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='news.newscategory', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'ordering': ['-publish_date'],
            },
        ),
    ]
