# Generated by Django 6.0 on 2026-01-05 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_category_post_comment_delete_news_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created_at',)},
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
