# Generated by Django 6.0 on 2026-01-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QabulKomissiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('familiya', models.CharField(max_length=100)),
                ('lavozim', models.CharField(max_length=50)),
                ('lavozim_turi', models.CharField(choices=[('rais', 'Komissiya raisi'), ('kotib', 'Mas’ul kotib'), ('azo', 'Komissiya a’zosi'), ('rahbar', 'Guruh rahbari')], default='azo', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefon', models.CharField(blank=True, max_length=20, null=True)),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='komissiya/')),
                ('tartib', models.PositiveIntegerField(default=0, help_text='Ekranda chiqish tartibi')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Qabul komissiya a’zosi',
                'verbose_name_plural': 'Qabul komissiya a’zolari',
                'ordering': ['tartib'],
            },
        ),
    ]
