# Generated by Django 6.0.1 on 2026-06-25 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_qabulkomissiya_lavozim'),
    ]

    operations = [
        migrations.CreateModel(
            name='IshAriza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='F.I.Sh')),
                ('nationality', models.CharField(choices=[('uzbek', "O'zbek"), ('other', 'Boshqa')], max_length=20, verbose_name='Millat')),
                ('nationality_other', models.CharField(blank=True, max_length=100, verbose_name='Boshqa millat')),
                ('address', models.CharField(max_length=300, verbose_name='Yashash manzili')),
                ('birth_date', models.DateField(verbose_name="Tug'ilgan sana")),
                ('education_level', models.CharField(choices=[('urta', "O'rta"), ('urta_maxsus', "O'rta maxsus / kasb-hunar"), ('oliy_bakalavr', 'Oliy (bakalavr)'), ('oliy_magistr', 'Oliy (magistr)'), ('oliy_doktorant', 'Oliy (doktorant / PhD)')], max_length=30, verbose_name="Ma'lumot")),
                ('education_diploma', models.FileField(upload_to='ish_ariza/diplom/', verbose_name="Ta'lim diplomi")),
                ('academic_title', models.CharField(blank=True, max_length=200, verbose_name='Ilmiy unvon')),
                ('academic_degree', models.CharField(blank=True, max_length=200, verbose_name='Ilmiy daraja')),
                ('foreign_language', models.CharField(blank=True, max_length=200, verbose_name='Xorijiy til darajasi')),
                ('institution', models.CharField(max_length=300, verbose_name="Ta'lim muassasasi")),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('reviewing', "Ko'rib chiqilmoqda"), ('approved', 'Qabul qilindi'), ('rejected', 'Rad etildi')], default='new', max_length=20, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt')),
            ],
            options={
                'verbose_name': "Ish o'rni arizasi",
                'verbose_name_plural': "Ish o'rni arizalari",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IshArizaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('academic_title', 'Ilmiy unvon diplomi'), ('academic_degree', 'Ilmiy daraja diplomi'), ('language_cert', 'Til sertifikati'), ('work_reference', "Mehnat faoliyati ma'lumotnomasi")], max_length=30)),
                ('file', models.FileField(upload_to='ish_ariza/files/')),
                ('ariza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='employees.ishariza')),
            ],
            options={
                'verbose_name': 'Ariza fayli',
                'verbose_name_plural': 'Ariza fayllari',
            },
        ),
    ]
