# Generated by Django 6.0.1 on 2026-06-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_ishariza_isharizafile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ishariza',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email manzil'),
        ),
        migrations.AddField(
            model_name='ishariza',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='Telefon raqam'),
        ),
    ]
