# Generated by Django 6.0.1 on 2026-06-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_ishariza_email_ishariza_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=50, unique=True)),
                ('step', models.CharField(default='full_name', max_length=50)),
                ('data', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bot sessiyasi',
                'verbose_name_plural': 'Bot sessiyalari',
            },
        ),
    ]
