# Generated by Django 6.0 on 2026-01-08 17:45

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MagistraturaNatijalari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Magistratura natijalari sahifasi matni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Magistratura',
                'verbose_name_plural': 'Magistratura',
            },
        ),
        migrations.CreateModel(
            name='QabulRijasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Qabul Rijasi sahifasi matni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'QabulRijasi',
                'verbose_name_plural': 'QabulRijasi',
            },
        ),
    ]
