# Generated by Django 6.0.1 on 2026-01-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignStudentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='F.I.Sh')),
                ('country', models.CharField(max_length=100, verbose_name='Davlat')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=30, verbose_name='Telefon raqam')),
                ('faculty', models.CharField(max_length=150, verbose_name='Qiziqqan yo‘nalish')),
                ('message', models.TextField(verbose_name='Murojaat matni')),
                ('admin_reply', models.TextField(blank=True, null=True, verbose_name='Qabul bo‘limi javobi')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('answered', 'Javob berildi')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Xorijiy talaba murojaati',
                'verbose_name_plural': 'Xorijiy talabalar murojaatlari',
            },
        ),
    ]
