# Generated by Django 6.0 on 2026-01-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignStudentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='F.I.Sh')),
                ('country', models.CharField(max_length=100, verbose_name='Davlat')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=30, verbose_name='Telefon raqam')),
                ('faculty', models.CharField(max_length=150, verbose_name='Tanlangan fakultet')),
                ('message', models.TextField(verbose_name='Qo‘shimcha ma’lumot')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Xorijiy talaba arizasi',
                'verbose_name_plural': 'Xorijiy talabalar arizalari',
            },
        ),
    ]
