# Generated by Django 6.0 on 2026-01-07 17:29

import django.db.models.deletion
import django.utils.timezone
import xorijiy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xorijiy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name="To'liq ism")),
                ('date_of_birth', models.DateField(verbose_name="Tug'ilgan sana")),
                ('gender', models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=10, verbose_name='Jinsi')),
                ('passport_number', models.CharField(max_length=50, verbose_name='Passport raqami')),
                ('passport_issue_date', models.DateField(verbose_name='Passport berilgan sana')),
                ('passport_expiry_date', models.DateField(verbose_name='Passport amal qilish muddati')),
                ('passport_photo', models.ImageField(upload_to=xorijiy.models.passport_upload_path, verbose_name='Passport nusxasi')),
                ('email', models.EmailField(max_length=254, verbose_name='Elektron pochta')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon raqami')),
                ('address', models.TextField(verbose_name='Yashash manzili')),
                ('city', models.CharField(max_length=100, verbose_name='Shahar')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Pochta indeksi')),
                ('previous_education', models.CharField(max_length=200, verbose_name="Oldingi ta'lim")),
                ('previous_institution', models.CharField(max_length=300, verbose_name="Oldingi o'quv muassasasi")),
                ('graduation_year', models.IntegerField(verbose_name='Bitirgan yili')),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=4, verbose_name="O'rtacha baho (GPA)")),
                ('diploma_copy', models.ImageField(upload_to=xorijiy.models.diploma_upload_path, verbose_name='Diplom nusxasi')),
                ('motivation_letter', models.TextField(verbose_name='Motivatsion xat')),
                ('emergency_contact_name', models.CharField(max_length=200, verbose_name='Favqulodda vaziyatdagi aloqa shaxsi')),
                ('emergency_contact_phone', models.CharField(max_length=50, verbose_name='Favqulodda aloqa telefon raqami')),
                ('application_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ariza sanasi')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('reviewed', "Ko'rib chiqilgan"), ('accepted', 'Qabul qilingan'), ('rejected', 'Rad etilgan'), ('waiting', "Kutish ro'yxatida")], default='new', max_length=20, verbose_name='Holati')),
                ('notes', models.TextField(blank=True, verbose_name='Izohlar')),
                ('confirmation_sent', models.BooleanField(default=False, verbose_name='Tasdiqlash xabari yuborilgan')),
                ('admin_notified', models.BooleanField(default=False, verbose_name='Administratorga xabar berilgan')),
            ],
            options={
                'verbose_name': 'Ariza',
                'verbose_name_plural': 'Arizalar',
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Mamlakat nomi')),
                ('code', models.CharField(max_length=10, verbose_name='Mamlakat kodi')),
            ],
            options={
                'verbose_name': 'Mamlakat',
                'verbose_name_plural': 'Mamlakatlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Dastur nomi')),
                ('code', models.CharField(max_length=50, verbose_name='Dastur kodi')),
                ('program_type', models.CharField(choices=[('bachelor', 'Bakalavr'), ('master', 'Magistr'), ('phd', 'PhD')], max_length=20, verbose_name='Dastur turi')),
                ('duration', models.IntegerField(verbose_name="O'qish muddati (yil)")),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': "O'quv dasturi",
                'verbose_name_plural': "O'quv dasturlari",
                'ordering': ['program_type', 'name'],
            },
        ),
        migrations.DeleteModel(
            name='ForeignStudentApplication',
        ),
        migrations.AddField(
            model_name='application',
            name='nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='xorijiy.country', verbose_name='Fuqarolik'),
        ),
        migrations.AddField(
            model_name='application',
            name='study_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='xorijiy.studyprogram', verbose_name="O'quv dasturi"),
        ),
    ]
