# Generated by Django 6.0.1 on 2026-01-08 11:04

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xorijiy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bakalaver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Bakalaver sahifasi matni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bakalaver',
                'verbose_name_plural': 'Bakalaver',
            },
        ),
        migrations.CreateModel(
            name='Kontrakt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Kontrakt sahifasi matni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kontrakt',
                'verbose_name_plural': 'Kontrakt',
            },
        ),
        migrations.CreateModel(
            name='Magistratura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Magistratura sahifasi matni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Magistratura',
                'verbose_name_plural': 'Magistratura',
            },
        ),
        migrations.CreateModel(
            name='Shartnomalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Shartnomalar sahifasi matni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Shartnomalar',
                'verbose_name_plural': 'Shartnomalar',
            },
        ),
    ]
