# Generated by Django 6.0.1 on 2026-01-07 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrivilegeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Kategoriya nomi')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon', models.CharField(help_text='Emoji yoki icon (👨\u200d👩\u200d👧\u200d👦)', max_length=10, verbose_name='Icon')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Imtiyoz kategoriyasi',
                'verbose_name_plural': 'Imtiyoz kategoriyalari',
            },
        ),
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Imtiyoz nomi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('documents', models.TextField(help_text='Har bir hujjatni yangi qatordan yozing', verbose_name='Kerakli hujjatlar')),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privileges', to='Abituriyent.privilegecategory', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Imtiyoz',
                'verbose_name_plural': 'Imtiyozlar',
                'ordering': ['order'],
            },
        ),
    ]
