# Generated by Django 6.0.1 on 2026-01-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Abituriyent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QabulKvotasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('file', models.FileField(upload_to='qabul_kvotasi/', verbose_name='Word fayl')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Qabul kvotasi',
                'verbose_name_plural': 'Qabul kvotalari',
            },
        ),
    ]
