# Generated by Django 6.0 on 2026-01-07 15:46

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Abituriyent', '0002_qabulkvotasi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qabulkvotasi',
            options={'verbose_name': 'Qabul kvotasi', 'verbose_name_plural': 'Qabul kvotasi'},
        ),
        migrations.RemoveField(
            model_name='qabulkvotasi',
            name='file',
        ),
        migrations.AddField(
            model_name='qabulkvotasi',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(default=1, verbose_name='Qabul kvotasi matni'),
            preserve_default=False,
        ),
    ]
