# Generated by Django 6.0.1 on 2026-01-08 10:10

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Abituriyent', '0003_alter_qabulkvotasi_options_remove_qabulkvotasi_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bakalaver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Bakalaver sahifasi matni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bakalaver',
                'verbose_name_plural': 'Bakalaver',
            },
        ),
    ]
