# Generated by Django 6.0.1 on 2026-01-08 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Abituriyent', '0004_bakalaver'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bakalaver',
        ),
    ]
