# Generated by Django 6.0 on 2026-01-04 17:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qabul_kom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('content', models.TextField(verbose_name='Mazmuni')),
                ('rule_type', models.CharField(choices=[('bakalavr', 'Bakalavriat'), ('magistr', 'Magistratura'), ('step', 'Bosqich'), ('general', 'Umumiy')], default='general', max_length=50, verbose_name='Qoida turi')),
                ('icon', models.CharField(default='fas fa-graduation-cap', max_length=100, verbose_name='Ikonka')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Qabul qoidasi',
                'verbose_name_plural': 'Qabul qoidalari',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('start_date', models.DateField(verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(verbose_name='Tugash sanasi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Muddat',
                'verbose_name_plural': 'Muddatlar',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Kategoriya nomi')),
                ('description', models.TextField(verbose_name='Kategoriya tavsifi')),
                ('icon', models.CharField(default='fas fa-file', max_length=100, verbose_name='Ikonka')),
                ('color', models.CharField(default='blue', max_length=50, verbose_name='Rang kodi')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hujjat kategoriyasi',
                'verbose_name_plural': 'Hujjat kategoriyalari',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ImportantNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('content', models.TextField(verbose_name='Mazmuni')),
                ('icon', models.CharField(default='fas fa-exclamation-circle', max_length=100, verbose_name='Ikonka')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Muhim eslatma',
                'verbose_name_plural': 'Muhim eslatmalar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Hujjat nomi')),
                ('description', models.TextField(verbose_name='Hujjat tavsifi')),
                ('file_format', models.CharField(choices=[('PDF', 'PDF'), ('DOC', 'DOC/DOCX'), ('JPG', 'JPG/JPEG/PNG'), ('XLS', 'XLS/XLSX'), ('ZIP', 'ZIP/RAR'), ('TXT', 'TXT')], max_length=10, verbose_name='Fayl formati')),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'xls', 'xlsx', 'zip', 'rar', 'txt'])], verbose_name='Fayl')),
                ('file_size', models.CharField(blank=True, max_length=50, verbose_name='Fayl hajmi')),
                ('download_count', models.IntegerField(default=0, verbose_name='Yuklab olishlar soni')),
                ('view_count', models.IntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib raqami')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='qabul_kom.documentcategory', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Hujjat',
                'verbose_name_plural': 'Hujjatlar',
                'ordering': ['order', 'name'],
            },
        ),
    ]
