# Generated by Django 6.0 on 2026-01-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qabul_kom', '0002_admissionrule_deadline_documentcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QabulJadvali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lavozim', models.CharField(max_length=100)),
                ('fish', models.CharField(max_length=150, verbose_name='F.I.Sh')),
                ('telefon', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('qabul_kuni', models.CharField(choices=[('Dushanba', 'Dushanba'), ('Seshanba', 'Seshanba'), ('Chorshanba', 'Chorshanba'), ('Payshanba', 'Payshanba'), ('Juma', 'Juma'), ('Shanba', 'Shanba')], max_length=20)),
                ('vaqt', models.CharField(max_length=50)),
                ('xona', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Qabul jadvali',
                'verbose_name_plural': 'Qabul jadvallari',
            },
        ),
    ]
