# Generated by Django 6.0 on 2026-01-05 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qabul_kom', '0003_qabuljadvali'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='category',
        ),
        migrations.DeleteModel(
            name='DocumentCategory',
        ),
    ]
