# Generated by Django 6.0 on 2026-01-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qabul_kom', '0004_remove_document_category_delete_documentcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'verbose_name': 'Qabul komissiyasi tarkibi ', 'verbose_name_plural': 'Qabul komissiyasi tarkibi'},
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(upload_to='team/', verbose_name='rasm 300 x 300 px '),
        ),
    ]
