# Generated by Django 6.0 on 2026-01-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qabul_kom', '0005_alter_teammember_options_alter_teammember_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='full_name',
            field=models.CharField(max_length=150, verbose_name='F.I.SH'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='profession',
            field=models.CharField(max_length=150, verbose_name='Lavozimi'),
        ),
    ]
