# Generated by Django 6.0 on 2026-01-07 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qabul_kom', '0006_alter_teammember_full_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
